history/urls.py
from django.urls import path
from . import views

app_name = 'history'
urlpatterns = [
    # Homepage
    # display all artists as links to details
    path('', views.index, name='index'),

    # localhost:8000/1/
    # display all song for artist
    path('<int:artist_id>/', views.detail, name='detail'),

    # localhost:8000/new_artist/ 
    # -- display form and POST
    path('new_artist/', views.new_artist, name='new_artist'),
    
    # localhost:8000/new_song/1
    # display song form and POST
    path('new_song/<int:artist_id>/', views.new_song, name='new_song'),
]

music/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('history.urls')),
    path('admin/', admin.site.urls),
]

history/models.py
from django.db import models

# Create your models here.

class Artist(models.Model):
    """Name of a musical artist"""
    name = models.CharField(max_length=200)

      
    def __str__(self):
        """return a string reppresentation of the model"""
        return self.name


class Song(models.Model):
    """Song names by musical artists"""
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        """return a string reppresentation of the model"""
        return self.name

history/forms.py
from django import forms
from .models import Artist, Song

class ArtistForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ['name']
        labels = {'name': ''}


class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['name']
        labels = {'name': ''}

history/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .models import Artist, Song
# from .forms import ArtistForm, SongForm

# Create your views here.

def index(request):
    """The home page for music history"""
    artist_list = Artist.objects.order_by('name')
    context = {
        'artist_list': artist_list,
        }
    return render(request, 'history/index.html', context)

def detail(request, artist_id):
    """the artist detail page"""
    artist = get_object_or_404(Artist, pk=artist_id)
    return render(request, 'history/detail.html', {'artist': artist})

#=============================================
# PCC way
#==============================================
# def new_artist(request):
#     """Add a new artist"""
#     if request.method != 'POST':
#         # No data submitted; create a blank form.
#         form = ArtistForm()
#     else:
#         # POST data submitted; process data.
#         form = ArtistForm(data=request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('history:index'))
        
#     context = {'form': form}
#     return render(request, 'history/new_artist.html', context)
# ===============================================

def new_artist(request):
    """Add new artist"""
    if request.method != 'POST':   
        return render(request, 'history/new_artist.html')
    else:
        artist = request.POST['artist_name']
        a = Artist(name = artist)
        a.save()
        return HttpResponseRedirect(reverse('history:index'))


#==============================================
# PCC Way
#==============================================
# def new_song(request, artist_id):
#     """Add a new song for a particular artist"""
#     artist = Artist.objects.get(id=artist_id)

#     if request.method != 'POST':
#         # No data submitted; create a blank form.
#         form = SongForm()
#     else:
#         # POST data submitted; process data.
#         form = SongForm(data=request.POST)
#         if form.is_valid():
#             # next 3 lines makes sure that you save the song 
#             # with the right artist id
#             new_song = form.save(commit=False)
#             new_song.artist = artist
#             new_song.save()
#             return HttpResponseRedirect(reverse('history:detail', args=[artist_id]))
    
#     context = {'artist': artist, 'form': form}
#     return render(request, 'history/new_song.html', context)
# ===============================================

def new_song(request, artist_id):
    """Add a new song for a particular artist"""
    artist = Artist.objects.get(id=artist_id)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        context = {'artist': artist}
        return render(request, 'history/new_song.html', context)
    else:
        # POST data submitted; process data.
        new_song=Song(name=request.POST['song_name'], artist_id=artist.id)
        new_song.save()
        return HttpResponseRedirect(reverse('history:detail', args=[artist_id]))
    
    

history/templates/history/base.html
 <p>
    <a href="{% url 'history:index' %}">Home</a>
</p>

{% block content %}{% endblock content %}

history/templates/history/detail.html
{% extends "history/base.html" %}

{% block content %}

    <h1>{{ artist.name }}</h1>

    
    <ul>
    {% for song in artist.song_set.all %}
        <li>{{ song.name }}</li>
    {% endfor %}
    </ul>

    <p>
        <button><a href="{% url 'history:new_song' artist.id %}">Add New Song</a></button>  
    </p>

    

{% endblock content %}

history/templates/history/index.html
{% extends "history/base.html" %}

{% block content %}

<p>Choose an Artist to See A Few of Their Songs:</p>

    <ul>
    {% for artist in artist_list %}
        <li>
            <a href="{% url 'history:detail' artist.id %}">
                {{ artist.name }}
            </a>
        </li>
    {% empty %}
        <li>No artists have been added yet.</li>
    {% endfor %}
    </ul>

    <button>
    <a href="{% url 'history:new_artist' %}">Add a New Artist</a>
    </button>


{% endblock content %}





history/templates/history/new_artist.html
{% extends "history/base.html" %}

{% block content %}
    <p>Add a New Artist</p>

    <form action="{% url 'history:new_artist' %}" method="post">
        {% csrf_token %}
        <input type="text" name="artist_name"/>
        <input type="submit" value="Add New Artist"/>
    </form>

{% endblock content %}

history/templates/history/new_song.html
{% extends "history/base.html" %}

{% block content %}
    <p>
        <a href="{% url 'history:detail' artist.id %}">
        {{ artist }}
        </a>
    </p>

    <p>Add a New Song:</p>

    <form action="{% url 'history:new_song' artist.id %}" method='post'>
        {% csrf_token %}
        <input type="text" name="song_name"/>
        <input type="submit" value="Add New Song"/>
    </form>


{% endblock content %}